<?php

// temp debug function
function wouwfotobeheer_init() {
  if ($_GET['page'] == 'debug') {
    // debugging
  }
}


function wouwfotobeheer_menu() {
  $items = null;
  
  $items['admin/settings/fotobeheer'] = array(
      'page callback' => 'wouwfotobeheer_settings',
  );
  
  return $items;
}

function wouwfotobeheer_settings() {
  $form = null;
  
  return '</pre>foo</pre>';
}

/**
 * Implementation of hook_nodeapi
 */
function wouwfotobeheer_nodeapi(&$node, $op, $a3 = null, $a4 = null) {
  if ($node->type == 'page' && $node->nid == 1224) {
    if ($op == 'view') {
      // inject fotobeheer module
    }
  }
}